/// <reference types="@cloudflare/workers-types" />

// glint telemetry collector.
//
// Accepts POST /v1/event with the schema documented in
// lib/src/observability/telemetry.dart. Writes one row to the
// `glint_events` Analytics Engine dataset per request.
//
// Anonymous: no auth, no IP capture in our blobs (CF still logs the
// edge IP at L4 — out of our hands). The body must include a UUIDv4
// `instance` field that the client generated.

// Generated by `wrangler types` — defines the EVENTS binding. Until
// the dev runs that locally we declare the minimal shape inline.
type AnalyticsEngineDataset = {
  writeDataPoint(point: {
    indexes?: string[];
    blobs?: string[];
    doubles?: number[];
  }): void;
};

interface Env {
  EVENTS: AnalyticsEngineDataset;
}

const ALLOWED_EVENTS = new Set([
  "tool_call",
  "session",
  "attach",
  "error",
]);

interface InboundEvent {
  v: number;
  instance: string;
  event: string;
  ts: string;
  platform?: string;
  fields: Record<string, unknown>;
}

const CORS_HEADERS: HeadersInit = {
  "access-control-allow-origin": "*",
  "access-control-allow-methods": "POST, OPTIONS",
  "access-control-allow-headers": "content-type",
  "access-control-max-age": "86400",
};

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    if (url.pathname === "/healthz" && request.method === "GET") {
      return new Response("ok\n", {
        status: 200,
        headers: { ...CORS_HEADERS, "content-type": "text/plain" },
      });
    }

    if (url.pathname !== "/v1/event") {
      return jsonError(404, "not found");
    }
    if (request.method !== "POST") {
      return jsonError(405, "method not allowed");
    }

    // Bound the body — telemetry payloads are tiny (< 1KB). Anything
    // larger is suspicious; reject without parsing.
    const lenHeader = request.headers.get("content-length");
    if (lenHeader && Number(lenHeader) > 4096) {
      return jsonError(413, "payload too large");
    }

    let body: InboundEvent;
    try {
      body = (await request.json()) as InboundEvent;
    } catch {
      return jsonError(400, "invalid json");
    }

    const issue = validate(body);
    if (issue) return jsonError(400, issue);

    // Write one row. Analytics Engine columns:
    //   indexes — high-cardinality query keys (instance, event)
    //   blobs   — string columns
    //   doubles — numeric columns
    try {
      env.EVENTS.writeDataPoint({
        indexes: [body.instance],
        blobs: [
          body.event,
          body.ts,
          body.platform ?? "",
          asString(body.fields.name),
          asString(body.fields.errorKind),
          asString(body.fields.op),
        ],
        doubles: [
          body.v,
          asNumber(body.fields.elapsedMs),
          asNumber(body.fields.armed) ? 1 : 0,
        ],
      });
    } catch (e) {
      console.error("analytics write failed", { err: String(e) });
      return jsonError(500, "write failed");
    }

    return new Response(null, { status: 204, headers: CORS_HEADERS });
  },
} satisfies ExportedHandler<Env>;

function validate(b: unknown): string | null {
  if (!isRecord(b)) return "body must be an object";
  if (b.v !== 1) return "unsupported schema version";
  if (typeof b.instance !== "string" || !UUID_V4.test(b.instance)) {
    return "instance must be a uuid v4";
  }
  if (typeof b.event !== "string" || !ALLOWED_EVENTS.has(b.event)) {
    return "event must be one of: tool_call, session, attach, error";
  }
  if (typeof b.ts !== "string" || isNaN(Date.parse(b.ts))) {
    return "ts must be an ISO-8601 timestamp";
  }
  if (b.platform !== undefined && typeof b.platform !== "string") {
    return "platform must be a string or absent";
  }
  if (!isRecord(b.fields)) return "fields must be an object";
  return null;
}

const UUID_V4 =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

function asString(v: unknown): string {
  return typeof v === "string" ? v : "";
}

function asNumber(v: unknown): number {
  return typeof v === "number" && Number.isFinite(v) ? v : 0;
}

function jsonError(status: number, message: string): Response {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { ...CORS_HEADERS, "content-type": "application/json" },
  });
}
