import 'dart:async';
import 'dart:convert';

import 'package:dart_mcp/server.dart';

import '../storage/captures_db.dart';
import '../util/scope.dart';
import 'error_kind.dart';
import 'result.dart';

const _kBodyTruncate = 8192;

final networkReplayAsTestTool = Tool(
  name: 'network_replay_as_test',
  description:
      'Emit a runnable Dart test (package:http + package:test) that replays a '
      'captured request and asserts its status code. Auth headers are redacted '
      '(commented out) by default. Lets the agent iterate a test instead of '
      're-driving the app.',
  inputSchema: Schema.object(
    properties: {
      'id': Schema.string(
        description: 'Request id from network_list / network_search.',
      ),
      'sessionId': Schema.int(
        description: 'Session to read. Omit to auto-resolve.',
      ),
      'appNameContains': Schema.string(
        description: 'Pick the session by app-name substring.',
      ),
      'assertBodyContains': Schema.string(
        description: 'Optional: also assert the response body contains this.',
      ),
      'redact': Schema.bool(
        description: 'Mask auth-like headers (default true).',
      ),
    },
    required: ['id'],
  ),
);

FutureOr<CallToolResult> networkReplayAsTest(CallToolRequest request) async {
  final args = request.arguments ?? const <String, Object?>{};
  final id = args['id'] as String?;
  if (id == null || id.isEmpty) {
    return errorResult('Missing required arg `id`.',
        kind: ErrorKind.badArgument,
        extra: const {
          'nextSteps': [
            'network_list — list captured requests and pick an id',
            'network_search query:"..." — find a request by content',
          ],
        });
  }
  final (scope, scopeErr) = resolveScope(args);
  if (scopeErr != null) return scopeErr;
  scope!;
  final sid = scope.sessionId;
  final redact = (args['redact'] as bool?) ?? true;
  final assertBodyContains = args['assertBodyContains'] as String?;

  final dao = CapturesDao();
  final row = dao.getHttpRequest(sid, id);
  if (row == null) {
    return errorResult('Request `$id` not found in session $sid.',
        kind: ErrorKind.notFound,
        extra: {
          'sessionId': sid,
          'nextSteps': const [
            'network_list — list valid ids in this session',
            'session_list — confirm the session exists',
          ],
        });
  }

  final method = ((row['method'] as String?) ?? 'GET').toUpperCase();
  final url = (row['url'] as String?) ?? '';
  final status = row['status_code'] as int?;
  final headers = _parseHeaders(row['request_headers_json']);
  final bodyBytes = dao.getBody(sid, id, 'request');
  final redactedSet = redact ? dao.redactedHeaderSet() : const <String>{};

  final headerLines = <String>[];
  var redactedCount = 0;
  if (headers != null) {
    for (final e in headers.entries) {
      final name = e.key;
      final value = e.value is List
          ? (e.value as List).join(', ')
          : (e.value?.toString() ?? '');
      if (redactedSet.contains(name.toLowerCase())) {
        redactedCount++;
        headerLines.add("      // '${_dartStr(name)}': '<fill in: redacted>',");
      } else {
        headerLines.add("      '${_dartStr(name)}': '${_dartStr(value)}',");
      }
    }
  }

  String? bodyLiteral;
  var bodyTruncated = false;
  if (bodyBytes != null && bodyBytes.isNotEmpty) {
    final clipped = bodyBytes.length > _kBodyTruncate
        ? bodyBytes.sublist(0, _kBodyTruncate)
        : bodyBytes;
    bodyTruncated = bodyBytes.length > _kBodyTruncate;
    try {
      bodyLiteral = _dartStr(utf8.decode(clipped));
    } catch (_) {
      bodyLiteral = null;
    }
  }

  final path = Uri.tryParse(url)?.path ?? url;
  final testName = '$method $path replays'.replaceAll("'", '');

  final b = StringBuffer();
  b.writeln("    final request = http.Request('$method', Uri.parse('${_dartStr(url)}'));");
  if (headerLines.isNotEmpty) {
    b.writeln('    request.headers.addAll({');
    for (final h in headerLines) {
      b.writeln(h);
    }
    b.writeln('    });');
  }
  if (bodyLiteral != null) {
    b.writeln("    request.body = '$bodyLiteral';");
  }
  b.writeln('    final response =');
  b.writeln('        await http.Response.fromStream(await request.send());');
  if (status != null) {
    b.writeln('    expect(response.statusCode, $status);');
  } else {
    b.writeln('    expect(response.statusCode, inInclusiveRange(200, 599));');
  }
  if (assertBodyContains != null && assertBodyContains.isNotEmpty) {
    b.writeln("    expect(response.body, contains('${_dartStr(assertBodyContains)}'));");
  }

  final code = '// Generated by flutter_network_mcp network_replay_as_test '
          '(request $id).\n'
          '// dev_dependencies: http, test. Fill in any redacted headers.\n'
          "import 'package:http/http.dart' as http;\n"
          "import 'package:test/test.dart';\n"
          '\n'
          'void main() {\n'
          "  test('$testName', () async {\n"
          '${b.toString().trimRight()}\n'
          '  });\n'
          '}\n';

  final warnings = <String>[
    if (redactedCount > 0)
      '$redactedCount auth header(s) are redacted (commented out); fill them '
          'in for the test to pass.',
    if (bodyTruncated)
      'Request body truncated at $_kBodyTruncate bytes.',
    if (status == null)
      'Original request had no captured status (in-flight); the test asserts a '
          '2xx-5xx range instead.',
    if (!redact)
      'Auth headers are NOT redacted; do not commit this test as-is.',
  ];

  return jsonResult({
    'scope': scope.toBlock(),
    'sessionId': sid,
    'summary': '$method $path -> Dart test emitted (asserts status '
        '${status ?? "2xx-5xx"}'
        '${assertBodyContains != null && assertBodyContains.isNotEmpty ? " + body contains" : ""}).',
    'id': id,
    'language': 'dart',
    'test': code,
    if (warnings.isNotEmpty) 'warnings': warnings,
    'nextSteps': [
      'Save the `test` string to test/<name>_test.dart and run `dart test`',
      'network_replay id:"$id" — get the equivalent curl instead',
    ],
  }, scopeSessionId: sid);
}

Map<String, dynamic>? _parseHeaders(Object? json) {
  if (json is! String || json.isEmpty) return null;
  try {
    final decoded = jsonDecode(json);
    return decoded is Map ? decoded.cast<String, dynamic>() : null;
  } catch (_) {
    return null;
  }
}

/// Escapes for a single-quoted Dart string literal.
String _dartStr(String s) => s
    .replaceAll(r'\', r'\\')
    .replaceAll(r'$', r'\$')
    .replaceAll("'", r"\'")
    .replaceAll('\r', r'\r')
    .replaceAll('\n', r'\n')
    .replaceAll('\t', r'\t');
